### ISSUE TITLE
Documentation on config file needed

### ISSUE THREAD

**Issue by zllovesuki** [Faithlife/sdc-portal#4]
I think right now we are scratching heads and trying to figure out the config file:

    "client" : {
        "auth": {
            "requestTokenUrl": "https://<your-endpoint-here>/initiate",
            "accessTokenUrl": "https://<your-endpoint-here>/token",
            "authorizeUrl": "https://<your-endpoint-here>/authorize",
            "consumerKey": "<your-consumer-key-here>",
            "consumerSecret": "<your-consumer-secret-here>",
            "callbackUrl": "http://localhost:8080/api/authorize",
            "getUserInfoUrl": "https://<your-endpoint-here>/"
        }
    }

I was under the impression that <your-endpoint-here> should be cloudapi URL?

Some more logs:

> sdc-portal 10:25:38 PM| info: D dataCenter:dataCenters:get:pending undefined
sdc-portal 10:25:38 PM| info: D user:users:pending undefined
sdc-portal 10:25:38 PM| info: < GET http://0.0.0.0:8080/api/datacenters
sdc-portal 10:25:38 PM| info: < GET http://0.0.0.0:8080/api/datacenters/test/users
sdc-portal 10:25:38 PM| info: GET /dependencies.bundle.js 500 15.646 ms - 1170
TypeError: Cannot read property 'params' of undefined
    at React.createClass.render (/root/sdc-portal/lib/components/app.jsx:57:147)
    at null.<anonymous> (/root/sdc-portal/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
    at wrapper [as _renderValidatedComponent] (/root/sdc-portal/node_modules/react/lib/ReactPerf.js:50:21)
    at null.<anonymous> (/root/sdc-portal/node_modules/react/lib/ReactCompositeComponent.js:802:14)
    at wrapper [as mountComponent] (/root/sdc-portal/node_modules/react/lib/ReactPerf.js:50:21)
    at null.<anonymous> (/root/sdc-portal/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/root/sdc-portal/node_modules/react/lib/ReactPerf.js:50:21)
    at null.<anonymous> (/root/sdc-portal/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/root/sdc-portal/node_modules/react/lib/ReactPerf.js:50:21)
    at /root/sdc-portal/node_modules/react/lib/ReactServerRendering.js:40:38
TypeError: Cannot read property 'params' of undefined
    at React.createClass.render (/root/sdc-portal/lib/components/app.jsx:57:147)
    at null.<anonymous> (/root/sdc-portal/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
    at wrapper [as _renderValidatedComponent] (/root/sdc-portal/node_modules/react/lib/ReactPerf.js:50:21)
    at null.<anonymous> (/root/sdc-portal/node_modules/react/lib/ReactCompositeComponent.js:802:14)
    at wrapper [as mountComponent] (/root/sdc-portal/node_modules/react/lib/ReactPerf.js:50:21)
    at null.<anonymous> (/root/sdc-portal/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/root/sdc-portal/node_modules/react/lib/ReactPerf.js:50:21)
    at null.<anonymous> (/root/sdc-portal/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at wrapper [as mountComponent] (/root/sdc-portal/node_modules/react/lib/ReactPerf.js:50:21)
    at /root/sdc-portal/node_modules/react/lib/ReactServerRendering.js:40:38

**Comment by richardkiene** [comment]
@zllovesuki The section you're pointing out is intended to be pointed at an OAuth endpoint. CloudAPI doesn't support auth yet, so we use an OAuth endpoint to get users IDs and map them to SDC users and keys.

I agree that the documentation could use some clarity there. One thing we hope to work on (or for someone to work on anyway) is adding OAuth to CloudAPI which would simplify this a lot.

**Comment by zllovesuki** [comment]
Hmm. I am guessing the sdc-portal is under this model:

![sdc-portal] (http://jerry.sh/Screen%20Shot%202015-04-23%20at%204.19.40%20PM.png)

Ideally, a panel like this would be a life saver:

![ideal] (http://jerry.sh/Screen Shot 2015-04-23 at 4.20.11 PM.png)

**Comment by richardkiene** [comment]
@zllovesuki Ideally we'll just add OAuth support to sdc-cloudapi and use SDC native accounts/logins. With that we won't need to add the complexity of a new data store, etc.

**Comment by zllovesuki** [comment]
@richardkiene Agree.

**Comment by lloydde** [comment]
I wasn't at Joyent when the decisions were made, but for JPC JPC portal, the data is stored in manta with redis in front of it. SDC native accounts are stored in ldap: sdc-ufds -> ldapjs.org. Only a small amount of configuration that is also applicable to adminui and cloudapi plugins gets promoted to be stored in ufds. LDAP isn't a general purpose data store. Also, there is significant maintenance and replication across availability zones implications.

When I worked on OpenStack 3 years ago, their design favored MySQL but different components might use their own DBMS and replication was very messy.

If the manta requirement is too heavy, to keep sdc-portal flexible, I would favor, at least initially, having it's own stateful storage, assuming using manta is untenable.

**Comment by richardkiene** [comment]
@lloydde Ah, that makes sense. I'm not sure we want Manta to be a requirement for sdc-portal, since not everyone will deploy it as a part of their SDC (including us, we just use JPC Manta for now). Having a local store and mapping to SDC native accounts seems reasonable, and non-ephemeral Redis seems like a good choice to me (MySQL just seems heavier than necessary and since you mentioned OpenStack, using MySQL with keystone is just painful and most have moved to memcached AFAIK).

**Comment by richardkiene** [comment]
@zllovesuki I suppose this gets us closer to your suggested implementation, would you be amenable to using Redis instead of Mongo?

@lloydde To clarify, are you essentially saying we should create another accounts system that maps to SDC native accounts, or are you suggesting we plumb the LDAP bits up to sdc-portal somehow and only use Redis for keys and metadata?

**Comment by lloydde** [comment]
@richardkiene I'm suggesting that unfortunately you'll want to consider having an additional persistent data store.

**Comment by zllovesuki** [comment]
@richardkiene @lloydde If I recall correctly, ALL services in SDC are stateless except Manatee, and Moray is acting as a key-value proxy to access Postgres. I wonder, why can't we squeeze another table (to store RSA keys) in Postgres? I have yet to fully explore the SDC architecture, but I have encountered some horrific moment (eg. https://jerry.im/essays/2015/04/smartdatacenter-admin-log-empty-owner-uuid-causes-problem/).

Anyway, I'm suggesting that we extend the existing architecture instead of adding more stuff. If we store RSA keys within Manatee, we can still make compatibility changes to sdc-portal so it can be used with CloudAPI (Because we need login, key, and keyid).

Yet again, storing RSA keys is stupid.

**Comment by richardkiene** [comment]
@zllovesuki In your picture you posted above, it appeared you wanted to store RSA keys in MongoDB, was I misunderstanding that? I think familiarizing yourself with the SDC APIs is a necessary step if we want to talk about making changes like plumbing Manatee access up to CloudAPI. Personally I can't imagine that Joyent would wan't that because CloudAPI is a public facing API and Manatee is core to the existence of the Admin network only APIs. Perhaps @lloydde can ring on on that.

**Comment by zllovesuki** [comment]
@richardkiene No you were correct, however @lloydde suggested that was "unfortunate". If we are going to add an additional database, HA will be another thing to consider.

**Comment by lloydde** [comment]
My comments are a bit tangental to the meat of this conversation, but I wanted to suggest that you shouldn't close yourself to yet-another-data-store as all self-server portals end up having user configuration and historic data that you'll need to store somewhere, too. Maybe, those aspects can be deferred with the current needs being appropriate for ufds.

![SDC Arch](https://raw.githubusercontent.com/joyent/sdc/master/docs/img/arch.png)

**Comment by lloydde** [comment]
What isn't in that picture is the JPC SSO and JPC Portal services. @richardkiene comment also reminds me, AFAIR, for working with ufds, you'll continue to need some intermediary service as ufds isn't secured for public access. The JPC SSO communicates with ufds through a vpn via a keyapi zone (similar to cloudapi). The jpc portal has its own user account and is enabled as a "developer" in ufds. This allows portal through sso to be delegated authentication on behalf of the user. The portal then makes regular CloudAPI requests.

JPC SSO is receiving minimum maintenance. The plan was to replace it with a common OAuth solution, but that work hasn't been prioritized in the six months since that decision was made nor is it on the plan for the next six months.

**Comment by richardkiene** [comment]
@zllovesuki @lloydde we worked a bit today on making a pluggable authentication provider. A pluggable auth provider gives us some flexibility and I think it will allow us to punt on a full blown solution inside of sdc-portal. Punting will hopefully allow for a longer discussion about how we can best help Joyent with a unified OAuth solution.

You can try out the pluggable authentication provider if you use the [schoonup](https://github.com/Faithlife/sdc-portal/tree/schoonup) branch. We hope to merge that code in to master over the weekend.

**Comment by zllovesuki** [comment]
So I spent 4 hours and came up something with this:

HTML: https://gist.github.com/zllovesuki/3d0795337f479082f4b8
Nginx.conf: https://gist.github.com/zllovesuki/43d6a79b58341c63bddd

Preflight:
Login into "cloudapi0", and add these:
>                restify.CORS.ALLOW_HEADERS.push('accept');
>                restify.CORS.ALLOW_HEADERS.push('api-version');
>                restify.CORS.ALLOW_HEADERS.push('authorization');
>                restify.CORS.ALLOW_HEADERS.push('x-date');
>                server.use(restify.CORS());

Before:

>                server.use(restify.fullResponse());

Restart your CloudAPI instance.

How-to test it:
1. Save the HTML to a file somewhere, it can be on a webserver, it can be on your desktop
2. Spin up a SmartMachine and install Nginx, replace /opt/local/etc/nginx.conf with config provided above for quick and dirty test, change the CloudAPI endpoint accordingly as well
3. Access the HTML and enter the Nginx IP, login, RSA_Key, and KeyId
4. Profit???

The original idea was to let the client provides RSA_Keys/keyId/login, and the client accesses CloudAPI directly, with no middleware/proxy. To prevent replay attack, CloudAPI requires "Date" header and the hash of the date. Unfortunately and also fortunately, modern browsers do not allow custom header of "Date", and ajax request does not add "Date" in the header, therefore we need a Nginx to proxy the request to the real CloudAPI. Instead of sending "Date", we are going to send "X-Date", so Nginx can proxy the request (X-Date to Date). 

The implication is that the RSA_Key can be stored in HTML5 local storage instead of a central database/datastore, and the Nginx instance can be very lightweight (it is only a proxy), probably 25%/50 LWPS/64MB/1024M can do it.

**Comment by richardkiene** [comment]
@zllovesuki This is definitely clever, however it appears to require a complete departure from the current architecture of sdc-portal (e.g. Switch to a dumb server offering up only HTML and JS). It also requires some fundamental changes to how clients interact with sdc-cloudapi (e.g. The addition of NGINX proxy and header translation).

In addition, doing in-browser crypto with JavaScript has inherent [issues](http://matasano.com/articles/javascript-cryptography/) that in the best case will raise some eyebrows and in the worst case will be less secure than hardened server key storage.

The abstraction of OAuth and other authentication providers, gives us the ability to map a single user to multiple keys, owners, and data centers, plus store metadata that wouldn't be easily stored in existing SDC APIs, etc. All while retaining the existing functionality of the AdminUI and key based access to CloudAPI.

I think at this point, we'd like to remain flexible with regard to the authentication mechanism used (e.g. pluggable authentication providers), but not get wrapped up in a [completionist](http://randsinrepose.com/archives/incrementalists-completionists/) view of the one true way to deal with key storage. In other words, I'd like to move forward with pluggable auth, and iterating the functionality of sdc-portal, but keep the discussion about key storage open.

I don't believe an RDBMS or Document Store is actually necessary at this point. Leaving the storage in the config file and local file system of the server actually retains the ability to scale out and be highly available w/ the flexibility to move that to a more centralized or decentralized storage mechanism in the future.

Since this conversation has moved far away from better documentation of the configuration file, I'd like to suggest that we move the conversation around key storage to https://beta.faithlife.com/sdc-portal/activity or the sdc-discuss mailing list.

**Comment by richardkiene** [comment]
@zllovesuki we've added pluggable auth providers, one of which is a no-auth "Admin Party" that should allow you to try out sdc-portal w/o worrying about the OAuth bits. In addition we've added a more concrete OAuth example and pointed to our publicly available OAuth endpoint and documentation at https://developer.faithlife.com in case people would like to give the OAuth provider a spin.

The commit that addresses this issue is [here](https://github.com/Faithlife/sdc-portal/commit/f965e2de4b7074a0235b7ac2d8eca94dcc52729a). I'll consider this case closed. Thank you so much for all your input!
